import { GoogleGenAI, Chat } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // In a real app, you might have better error handling or a fallback.
  // For this context, we'll proceed assuming it's set in the environment.
  throw new Error("Gemini API key not found. AI features will not work.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const schema = `
-- Database Schema for a School Management System

CREATE TABLE public.owner (
  uid uuid NOT NULL PRIMARY KEY,
  school_name text NOT NULL,
  principal_name text,
  mobile_number text NOT NULL,
  school_image_url text,
  register_date timestamp with time zone NOT NULL DEFAULT now(),
  address text,
  website text,
  school_code text UNIQUE
);

CREATE TABLE public.staff (
  id bigint GENERATED ALWAYS AS IDENTITY,
  uid uuid NOT NULL,
  staff_id text UNIQUE,
  name text,
  mobile text,
  gmail text,
  father_name text,
  mother_name text,
  address text,
  password text,
  highest_qualification text,
  joining_date date,
  photo_url text,
  salary_amount numeric,
  total_paid numeric DEFAULT 0,
  total_dues numeric DEFAULT 0,
  previous_dues numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  -- monthly payment tracking
  january date, february date, march date, april date, may date, june date, july date, august date, september date, october date, november date, december date,
  PRIMARY KEY (id, uid)
);

CREATE TABLE public.students (
  id bigint GENERATED ALWAYS AS IDENTITY,
  uid uuid NOT NULL,
  roll_number text,
  name text,
  mobile text,
  gmail text,
  password text,
  father_name text,
  mother_name text,
  class text,
  address text,
  photo_url text,
  aadhar text,
  gender text,
  date_of_birth date,
  registration_date timestamp with time zone DEFAULT now(),
  caste text,
  blood_group text,
  previous_school_name text,
  other_fees jsonb, -- Array of other fees {fees_name, amount, dues_date, paid_date}
  -- monthly fee tracking
  january text DEFAULT 'undefined', february text DEFAULT 'undefined', march text DEFAULT 'undefined', april text DEFAULT 'undefined', may text DEFAULT 'undefined', june text DEFAULT 'undefined', july text DEFAULT 'undefined', august text DEFAULT 'undefined', september text DEFAULT 'undefined', october text DEFAULT 'undefined', november text DEFAULT 'undefined', december text DEFAULT 'undefined',
  previous_dues numeric,
  PRIMARY KEY (id, uid)
);

CREATE TABLE public.classes (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL,
  class_name text NOT NULL,
  staff_id text, -- staff_id of class teacher
  school_fees numeric
);

CREATE TABLE public.subjects (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL,
  subject_name text NOT NULL
);

CREATE TABLE public.assign_class (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL,
  class_id bigint NOT NULL,
  subject_id bigint NOT NULL,
  staff_id text,
  incoming_time time without time zone,
  outgoing_time time without time zone
);

CREATE TABLE public.attendance (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL,
  class_id bigint NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  present text, -- Can be a JSON array of student IDs
  absent text   -- Can be a JSON array of student IDs
);

CREATE TABLE public.staff_attendence (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL,
  staff_id text, -- Comma-separated staff IDs
  date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.expenses (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL,
  date date NOT NULL,
  category text NOT NULL,
  notes text,
  amount numeric NOT NULL
);

CREATE TABLE public.fees_types (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL,
  fees_name text NOT NULL,
  amount numeric NOT NULL,
  frequency text -- e.g., 'monthly', 'yearly', 'one-time'
);

CREATE TABLE public.salary_records (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL,
  staff_id text NOT NULL,
  date_time timestamp with time zone NOT NULL DEFAULT now(),
  amount numeric NOT NULL,
  notes text
);

CREATE TABLE public.exam_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  exam_name text NOT NULL,
  class text NOT NULL,
  roll_number text NOT NULL,
  subjects_marks jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.driver (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  uid uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  driver_id text UNIQUE,
  name text NOT NULL,
  mobile text NOT NULL,
  aadhar text,
  photo_url text,
  address text,
  van_number text NOT NULL,
  van_image_url text,
  driving_licence text,
  students_list jsonb -- Array of {class, roll_number, name}
);
`;


const systemInstruction = `
You are a friendly and expert assistant for the 'My Zini' school management ERP software. Your primary goal is to help school owners and staff use the application effectively.

Your capabilities include:
1.  **Answering Questions:** Respond to user queries about their school data based on the provided database schema. Interpret their natural language and provide clear, concise summaries in a user-friendly markdown format. Do not generate SQL.
2.  **Guiding Users:** Provide helpful instructions on how to use the 'My Zini' software. For example, if a user asks "how do I add a new student?", explain the steps by navigating to the 'Students' page and clicking the 'Add New Student' button.
3.  **Explaining Features:** Describe the purpose and benefits of different modules within the ERP (like Dashboard, Attendance, Results, etc.). Highlight how this ERP can streamline their work.
4.  **Multi-language Support:** ALWAYS respond in the same language the user uses for their query.
5.  **Image Analysis:** If the user uploads an image (like a screenshot of a table or a document), analyze it and answer questions related to it.

Here is the database schema for your reference:
${schema}
`;

export function startChatWithHistory(): Chat {
    return ai.chats.create({
        model: 'gemini-2.5-flash',
        config: {
            systemInstruction: systemInstruction,
        },
    });
}